#!/usr/bin/env python3
"""Build the TEST screenplay as Pulp's element array, verify >=10 pages, POST to live API."""
import json, math, secrets, urllib.request

API = "https://pulp-phi.vercel.app/api/documents"

def nid():
    return secrets.token_urlsafe(6)[:8]

E = []  # element list
def add(t, text):
    E.append({"id": nid(), "type": t, "text": text})

# convenience element builders
def scene(s): add("scene", s)
def action(s): add("action", s)
def char(s): add("character", s)
def paren(s): add("parenthetical", s)
def dlg(s): add("dialogue", s)
def trans(s): add("transition", s)

# ============================================================
# THE LEDGER — a 10+ page investigative thriller (test fixture)
# ============================================================

trans("FADE IN:")

scene("INT. RIVERSIDE PRESS — NEWSROOM — NIGHT")
action("Rain hammers the floor-to-ceiling windows. A cathedral of dead monitors, except one. MAYA VANCE (30s, sharp, sleepless) sits in its blue glow, surrounded by printouts pinned into a constellation only she understands.")
action("A wall clock reads 2:14 AM. Maya scrolls a spreadsheet. Her finger stops.")
char("MAYA")
paren("under her breath")
dlg("That's not a rounding error. That's a door.")
action("She drags a column. Numbers cascade. A pattern blooms — the same figure, hidden across forty subsidiaries.")
char("MAYA (CONT'D)")
dlg("Forty shells, one hand. Hello.")
action("Behind her, the elevator DINGS. She doesn't turn. A reflection grows in the dark glass — a man in a wet overcoat.")
char("DEREK")
dlg("You're here late.")
char("MAYA")
paren("not looking up")
dlg("I'm always here. You're the variable, Derek.")
action("DEREK HALE (50s, editor, tired in his bones) drops a coffee beside her keyboard. It's the wrong order. He always gets it wrong.")
char("DEREK")
dlg("Oat milk. Two sugars. Like a child.")
char("MAYA")
dlg("Like a person who wants to live past sixty. Sit down. Look at this.")
action("Derek leans in. The smile drains from his face as the numbers resolve.")
char("DEREK")
paren("quietly")
dlg("Where did you get this?")
char("MAYA")
dlg("A man who's now afraid of his own phone. He gave me a spreadsheet and a name.")
char("DEREK")
dlg("Don't say the name.")
char("MAYA")
dlg("Halloran.")
action("Derek straightens like he's been slapped. He glances at the dark office, the empty desks, the single working light.")
char("DEREK")
dlg("In this building, you whisper that name. You don't type it.")
trans("SMASH CUT TO:")

scene("INT. RIVERSIDE PRESS — DEREK'S OFFICE — CONTINUOUS")
action("Glass walls, lower light. Derek shuts the blinds — an act that feels, somehow, like an admission. Maya stands with her arms folded.")
char("DEREK")
dlg("Eight years ago I had a reporter on Halloran. Good kid. Better than good.")
char("MAYA")
dlg("What happened to him?")
char("DEREK")
paren("a beat")
dlg("He took a job in PR. For Halloran. Drives a very nice car now. Doesn't return my calls.")
char("MAYA")
dlg("So he was bought.")
char("DEREK")
dlg("Or he was warned, and 'bought' was the polite version. Maya — if this is real, it isn't a story about money.")
char("MAYA")
dlg("Everything's a story about money.")
char("DEREK")
dlg("It's a story about what people will do to keep money quiet.")
action("Maya places a small recorder on his desk. Presses PLAY. A frightened male VOICE crackles out.")
char("VOICE (V.O.)")
paren("filtered, shaking")
dlg("They move it through the foundation. The charity is the laundromat. Look at the grant nobody received.")
action("Click. Silence. Derek stares at the recorder like it might bite.")
char("DEREK")
dlg("Who is that?")
char("MAYA")
dlg("My source. I call him Lighthouse. He calls me at 3 AM and hangs up if a car slows down outside.")
char("DEREK")
dlg("Get a second source. Get documents. Get everything twice. Because the second you publish, they will come for the one thing they can break.")
char("MAYA")
dlg("Which is?")
char("DEREK")
dlg("You.")
trans("CUT TO:")

scene("EXT. CITY STREET — NIGHT")
action("Maya walks fast under failing streetlights, collar up. Her phone BUZZES. UNKNOWN NUMBER. She answers without breaking stride.")
char("MAYA")
dlg("Vance.")
char("LIGHTHOUSE (V.O.)")
paren("breathless")
dlg("Did you look at the grant?")
char("MAYA")
dlg("I'm looking at everything. I need you to meet me. In daylight. With paper.")
char("LIGHTHOUSE (V.O.)")
dlg("Paper gets people killed.")
char("MAYA")
dlg("So does silence. It's just slower.")
action("A black SUV rolls past, too slow. Maya clocks it, ducks into a 24-hour diner, and keeps the phone to her ear.")
char("LIGHTHOUSE (V.O.)")
dlg("There's a unit. Storage facility on Pier 9. Locker 114. If anything happens to me—")
char("MAYA")
dlg("Nothing happens to you. Pier 9, Locker 114. What's the combination?")
char("LIGHTHOUSE (V.O.)")
dlg("The year it all started. You'll know it when you've read enough.")
action("The line goes dead. Maya looks out the window. The SUV is gone. Somehow that's worse.")
trans("DISSOLVE TO:")

scene("INT. MAYA'S APARTMENT — DAWN")
action("A small flat drowning in research. Maya pins a photo of a gleaming charity gala to the wall — smiling executives, champagne, a banner: THE HALLORAN FOUNDATION: BUILDING TOMORROW.")
action("She circles one face in red marker. RICHARD HALLORAN (60s), the kind of handsome that money buys and keeps.")
char("MAYA")
paren("to the photo")
dlg("Building tomorrow. On whose yesterday?")
action("Her laptop CHIMES. An email. No subject. One line.")
action("INSERT — THE SCREEN: 'STOP LOOKING. — A FRIEND.'")
action("Maya stares. Then, slowly, she smiles. It is not a comforting smile.")
char("MAYA")
dlg("Friends don't use block capitals.")
trans("SMASH CUT TO:")

scene("INT. HALLORAN FOUNDATION — EXECUTIVE FLOOR — DAY")
action("Glass, marble, the hush of serious wealth. Richard Halloran stands at a window owning the skyline. Behind him, his fixer, CLAIRE VOSS (40s, immaculate, lethal), reads from a tablet.")
char("CLAIRE")
dlg("A reporter. Riverside Press. Maya Vance. She's pulled the subsidiary filings — all forty.")
char("HALLORAN")
paren("not turning")
dlg("Forty's a lot of reading for a girl with a deadline.")
char("CLAIRE")
dlg("She's not reading. She's mapping. There's a difference, and she's good at it.")
char("HALLORAN")
dlg("Then we make her a better offer than the truth. Everyone has a number, Claire.")
char("CLAIRE")
dlg("And the ones who don't?")
action("Halloran finally turns. His smile is warm. His eyes are not.")
char("HALLORAN")
dlg("Then they have something they love more than they hate me. Find it.")
trans("CUT TO:")

scene("EXT. PIER 9 — STORAGE FACILITY — DAY")
action("Wind off the water. Rows of identical orange doors. Maya finds LOCKER 114 and crouches at the combination dial, sorting through years in her head.")
char("MAYA")
paren("muttering")
dlg("The year it all started...")
action("She tries a date. Nothing. Another. Nothing. Then she remembers a footnote — the year the Foundation was 'founded.' She spins it in.")
action("The lock POPS. She rolls the door up on a single cardboard box. Inside: ledgers. Real, physical, ink-and-paper ledgers.")
char("MAYA")
paren("breathless")
dlg("Oh, you beautiful, stupid, honest man. You kept the paper.")
action("Footsteps on gravel behind her. She freezes, then turns — it's a JANITOR with a mop bucket, utterly bored. He nods. She exhales a year's worth of air.")
char("JANITOR")
dlg("You lost?")
char("MAYA")
dlg("Just found, actually. First time in a while.")
trans("DISSOLVE TO:")

scene("INT. RIVERSIDE PRESS — NEWSROOM — NIGHT")
action("The ledgers fan across two desks. Derek photographs each page. Maya cross-references against the digital filings, and the two records — paper and pixel — refuse to agree. That disagreement is the whole story.")
char("DEREK")
dlg("The charity reports a grant. The recipient never existed. The money lands in a subsidiary that buys a building from another subsidiary—")
char("MAYA")
dlg("—at ten times its value. Clean money out the other end. It's a car wash with a tax exemption.")
char("DEREK")
dlg("This is enough.")
char("MAYA")
paren("shaking her head")
dlg("It's enough to get sued. I want enough to get convictions.")
char("DEREK")
dlg("You want a confession.")
char("MAYA")
dlg("I want him to say it. On the record. In his own beautiful voice.")
char("DEREK")
dlg("He'll never sit down with you.")
char("MAYA")
dlg("He will if he thinks he's buying me.")
trans("CUT TO:")

scene("INT. HALLORAN FOUNDATION — HALLORAN'S OFFICE — DAY")
action("Maya sits across from Halloran. Two coffees between them. Claire stands by the door like a closed exit. Maya sets her phone on the table, screen up, recording — openly.")
char("HALLORAN")
paren("amused")
dlg("Most people hide the recorder.")
char("MAYA")
dlg("Most people are ashamed of what they're doing. I'm not.")
char("HALLORAN")
dlg("Neither am I. I build hospitals, Miss Vance. Schools. I move money so that good things can stand where bad things were.")
char("MAYA")
dlg("Through forty shell companies?")
char("HALLORAN")
paren("smiling")
dlg("Through whatever the law allows. Which is more than you'd like.")
char("MAYA")
dlg("The Mercer grant. Two-point-four million. The recipient doesn't exist.")
action("A flicker. Just one. Halloran sets down his cup.")
char("HALLORAN")
dlg("Careful. The next sentence you say is the one your lawyers will read aloud for years.")
char("MAYA")
dlg("Then let me say it clearly, so they don't have to squint. You laundered public charity through phantom grants and you've done it for a decade.")
action("Silence. Claire steps forward. Halloran raises one finger — stop. He studies Maya like a chess problem he's already solved.")
char("HALLORAN")
dlg("What's your number?")
char("MAYA")
dlg("There isn't one.")
char("HALLORAN")
dlg("There's always a number.")
char("MAYA")
paren("standing")
dlg("Not for me. And that should frighten you more than any subpoena.")
action("She picks up her phone. Stops the recording with a single, deliberate tap. Smiles.")
char("MAYA (CONT'D)")
dlg("Thank you for your time, Mr. Halloran. You've been very generous with it.")
trans("CUT TO:")

scene("INT. MAYA'S APARTMENT — NIGHT")
action("Maya bursts in, electric. She drops her bag, pulls up the recording, hits PLAY to confirm she got it. Halloran's voice fills the room — then CUTS to static.")
action("She frowns. Scrubs back. Static. The file is corrupted — or was corrupted. Her face falls.")
char("MAYA")
dlg("No. No, no, no—")
action("Her phone BUZZES. A text from CLAIRE VOSS: 'Nice try. We own the cloud too. — A friend.'")
action("Maya sinks onto the floor against the wall, surrounded by her constellation of proof, holding a phone full of nothing.")
char("MAYA")
paren("whispering")
dlg("Then I'll write it from the paper. They can't corrupt a box.")
action("A long beat. Then her eyes lift to the window — and the black SUV parked across the street, engine off, lights dark, waiting.")
trans("SMASH CUT TO:")

scene("EXT. RIVERSIDE PRESS — LOADING DOCK — NIGHT")
action("Maya hauls the cardboard box from a taxi, glancing over her shoulder. Derek waits at the door, holding it open, eyes scanning the street.")
char("DEREK")
dlg("Tell me you have the audio.")
char("MAYA")
dlg("They killed the audio. We go with the ledgers. Photographed, notarized, three copies, three cities.")
char("DEREK")
dlg("And Lighthouse?")
char("MAYA")
paren("a beat, hollow")
dlg("He hasn't called in two days.")
action("Derek takes the box from her hands. For a moment they just stand there, two people about to set a building on fire and call it journalism.")
char("DEREK")
dlg("Once we publish, there's no taking it back.")
char("MAYA")
dlg("Good. I'm tired of taking things back.")
trans("CUT TO:")

scene("INT. RIVERSIDE PRESS — NEWSROOM — DAWN")
action("The story is built. On screen: a headline, a byline, a fortress of footnotes. Maya's cursor hovers over PUBLISH. The newsroom is silent, holding its breath with her.")
char("DEREK")
dlg("For the record — I'm proud of you. And I'm terrified.")
char("MAYA")
dlg("That's the job. Pride and terror, in equal columns.")
action("Her phone BUZZES. UNKNOWN NUMBER. She answers, eyes still on the screen.")
char("MAYA (CONT'D)")
dlg("Vance.")
char("LIGHTHOUSE (V.O.)")
paren("alive, exhausted, somewhere far away")
dlg("Did you publish?")
char("MAYA")
paren("a slow smile")
dlg("About to. Where have you been?")
char("LIGHTHOUSE (V.O.)")
dlg("Somewhere with no slow cars. Print it, Maya. Print all of it.")
action("Maya looks at Derek. He nods. She clicks PUBLISH.")
action("The screen refreshes. LIVE. The story is out in the world, beyond recall, beyond purchase, beyond the reach of any friend who writes in block capitals.")
char("MAYA")
paren("quietly, to no one and everyone")
dlg("Building tomorrow.")
action("She leans back. Through the great windows, the city begins to wake — and somewhere across town, a phone rings in a marble office, and rings, and rings, and no one beautiful answers it.")
trans("FADE OUT.")

action("THE END")

# ---- Title page ----
title_page = {
    "title": "THE LEDGER",
    "author": "Vansh Kunal Shah",
    "basedOn": "based on a true pattern",
    "contact": "vansh@pulp.app\n+44 7700 900000\nRepresentation: Riverside Press",
    "draftDate": "First Draft \u00b7 June 17, 2026",
}

# ---- page estimate (mirror src/lib/screenplay.ts) ----
LINES_PER_PAGE = 55
CHARS = {"scene":60,"action":60,"character":38,"dialogue":35,"parenthetical":25,"transition":60}
lines = 0
for el in E:
    w = CHARS.get(el["type"],60)
    lines += max(1, math.ceil((len(el["text"]) or 1)/w)) + 1
pages = round((lines/LINES_PER_PAGE)*10)/10

counts = {}
for el in E:
    counts[el["type"]] = counts.get(el["type"],0)+1

print(f"Elements: {len(E)}")
print(f"Element breakdown: {json.dumps(counts)}")
print(f"Estimated pages: {pages}")

payload = {"title":"TEST","mode":"screenplay","content":E,"synopsis":json.dumps(title_page)}

if pages < 10:
    print(f"WARNING: only {pages} pages — under 10.")
else:
    print(f"OK: {pages} pages >= 10.")

# write payload to file for the POST step
with open("/home/user/workspace/pulp/test_payload.json","w") as f:
    json.dump(payload,f)
print("payload written.")
